[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
here = "9vxxPimLzVMLiDf788mTzJyv66EvtyJpZXS9ZYq8JZjo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = '~\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
